version: '3.8'
services:
  landing-page:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: landing-page-app
    ports:
      - "8085:8085"
    restart: unless-stopped
    networks:
      - vendor-management-tool_vendor-network

networks:
  vendor-management-tool_vendor-network:
    external: true
